### ISSUE TITLE
cf托管的聊天记录在微信被屏蔽

### ISSUE THREAD

**Issue by magisk317** [Clansty/Q2TG#109]
现象如下:
![Screenshot_2023-04-05-09-57-53-842_com tencent mm](https://user-images.githubusercontent.com/93979778/229961458-f6999ee8-fadc-49c2-b9f6-10820b402c67.jpg)
可以通过站长认证，添加验证文件:
![IMG_20230405_094626](https://user-images.githubusercontent.com/93979778/229961531-3cdc6983-bf1f-4b10-887e-f0d2a24fd5a3.jpg)
但是我看了下cf的记录，貌似只上传了这几个文件:
![Screenshot_2023-04-05-09-46-08-377_com android chrome](https://user-images.githubusercontent.com/93979778/229961620-4a6681f3-e797-4d0c-943b-a766fe77320f.jpg)
所以想问下，这个文件我在仓库根目录建好了，怎么让一起上传上去呢，谢谢

**Comment by origami-owo** [comment]
建议绑定自己域名

**Comment by clansty** [comment]
应该有静态资产文件目录

以及为什么要在微信打开聊天记录页面，不应该只在 tg 打开吗

拒绝马化腾张小龙从我做起
