### ISSUE TITLE
目前无法登录

### ISSUE THREAD

**Issue by StephenSSR** [Clansty/Q2TG#115]
目前已经不能正常登录，会遇到`ENOENT: no such file or directory, unlink '/app/data/*****/token.json'`报错

**Comment by linep4** [comment]
请问怎么解决的，我一直token失效，用的是dockers-compose部署
`Package Version: oicq@2.3.3-clansty (Released on 2022/12/26)`
`View Changelogs：https://github.com/takayama-lily/oicq/releases`
`********:8080 connected`
`登录token过期`
`ENOENT: no such file or directory, unlink '/app/data/******/token'`
