### ISSUE TITLE
token失效

### ISSUE THREAD

**Issue by linep4** [Clansty/Q2TG#119]
用的是dockers-compose部署
Package Version: oicq@2.3.3-clansty (Released on 2022/12/26)
View Changelogs：https://github.com/takayama-lily/oicq/releases
********:8080 connected
登录token过期
ENOENT: no such file or directory, unlink '/app/data/******/token'

**Comment by linep4** [comment]
换了个镜像就可以了

**Comment by sbbbsbbb** [comment]
请问换的哪个镜像

**Comment by linep47** [comment]
> 请问换的哪个镜像

rainbowcat这个可以用，项目是非常棒的，但是q2tg我用着不太稳定不知道为什么，现在用QQ比较少了
