### ISSUE TITLE
登录过期后无法再次登录

### ISSUE THREAD

**Issue by retX0** [Clansty/Q2TG#12]
登录过期后无法再次登录，使用命令 `docker logs -f main_q2tg` 查看日志，日志一直输出

```
[2022-04-XXT08:53:58.896] [MARK] [Watch:672998436] - 请用手机QQ扫描二维码，若打印出错请打开：/app/data/672998436/qrcode.png
[2022-04-XXT08:53:59.027] [ERROR] [Watch:672998436] - 二维码扫码遇到错误: 48 (二维码尚未扫描)
```

**Comment by clansty** [comment]
PR Welcome

**Comment by zsbai** [comment]
这种情况是需要重新setup吗？我也是这样子，扫码之后终端还是一直输出二维码

**Comment by zsbai** [comment]
> 这种情况是需要重新setup吗？我也是这样子，扫码之后终端还是一直输出二维码

发现了...二维码更新的频率很高，一秒一更新

**Comment by THU-Pieris** [comment]
同样的问题。请问这个情况下应该如何再次登陆？

**Comment by retX0** [comment]
> 同样的问题。请问这个情况下应该如何再次登陆？

我是直接把数据库删掉了重新部署的

**Comment by iceBear67** [comment]
也遇到了这个问题，而且删掉数据库重部署也没有起效

**Comment by zsbai** [comment]
> 也遇到了这个问题，而且删掉数据库重部署也没有起效

需要删除掉data文件夹重新部署
