### ISSUE TITLE
兩個 docker-compose.yaml 不一致

### ISSUE THREAD

**Issue by ayaka14732** [Clansty/Q2TG#121]
rainbowcat 和 raincandy 分支的不一樣，主分支是 rainbowcat，但是《[安装部署](https://github.com/Clansty/Q2TG/wiki/%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2)》裏是 raincandy，應該以哪個為準？

**Comment by magisk317** [comment]
> rainbowcat 和 raincandy 分支的不一樣，主分支是 rainbowcat，但是《[安装部署](https://github.com/Clansty/Q2TG/wiki/%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2)》裏是 raincandy，應該以哪個為準？

肯定是raincandy，rainbowcat还在开发中，且二者不兼容

**Comment by clansty** [comment]
应该使用 rainbowcat。因为 raincandy 分支已经停止支持，并且没有更新新的签名服务器支持。rainbowcat 是一个 breakchange，所以更换到了新的分支。wiki 里面的链接是忘记换了
