### ISSUE TITLE
登录token过期

### ISSUE THREAD

**Issue by ayaka14732** [Clansty/Q2TG#122]
无法登录：

```
[2023-05-23T11:17:06.090] [MARK] [iMac:******] - 收到滑动验证码，请访问以下地址完成滑动，并从网络响应中取出ticket输入：https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?******
[2023-05-23T11:17:25.975] [MARK] [iMac:******] - 登录token过期
[2023-05-23T11:17:25.976] [FATAL] [iMac:******] - ENOENT: no such file or directory, unlink '/app/data/******/token'
```

**Comment by magisk317** [comment]
没用的，就算不过期，你也登不上去
![image](https://github.com/Clansty/Q2TG/assets/93979778/4078491c-5ae8-44cc-b650-caddc0952764)

**Comment by yuioto** [comment]
类似问题，但仅报告token过期，没有要求通过滑动验证码。
我要如何做才能刷新我的token？
@Clansty 

```log
2023-07-01T12:04:32.603430652Z [2023-07-01T12:04:32.602] [MARK] [aPad:qqid*****] - 登录token过期
2023-07-01T12:04:32.605762188Z [2023-07-01T12:04:32.605] [FATAL] [aPad:qqid*****] - ENOENT: no such file or directory, unlink '/app/data/qqid*****/token'
```

## docker vision

`docker -v`

```log
Docker version 24.0.2, build cb74dfcd85
```

`docker-compose -v`

```log
Docker Compose version 2.19.1
```

## 其他可能有用命令输出

`docker-compose images`

```log
CONTAINER           REPOSITORY             TAG                 IMAGE ID            SIZE
main_q2tg           ghcr.io/clansty/q2tg   raincandy           38a2332027fc        1.21GB
postgresql_q2tg     postgres               14-alpine           2e0bc99c553f        235MB
```
`docker-compose pull  `

```log
[+] Pulling 2/2
 ✔ postgres Pulled                                                   1.0s 
 ✔ q2tg Pulled
```

**Comment by sbbbsbbb** [comment]
> 类似问题，但仅报告token过期，没有要求通过滑动验证码。 我要如何做才能刷新我的token？ @Clansty
> 
> ```
> 2023-07-01T12:04:32.603430652Z [2023-07-01T12:04:32.602] [MARK] [aPad:qqid*****] - 登录token过期
> 2023-07-01T12:04:32.605762188Z [2023-07-01T12:04:32.605] [FATAL] [aPad:qqid*****] - ENOENT: no such file or directory, unlink '/app/data/qqid*****/token'
> ```
> 
> ## docker vision
> `docker -v`
> 
> ```
> Docker version 24.0.2, build cb74dfcd85
> ```
> 
> `docker-compose -v`
> 
> ```
> Docker Compose version 2.19.1
> ```
> 
> ## 其他可能有用命令输出
> `docker-compose images`
> 
> ```
> CONTAINER           REPOSITORY             TAG                 IMAGE ID            SIZE
> main_q2tg           ghcr.io/clansty/q2tg   raincandy           38a2332027fc        1.21GB
> postgresql_q2tg     postgres               14-alpine           2e0bc99c553f        235MB
> ```
> 
> `docker-compose pull `
> 
> ```
> [+] Pulling 2/2
>  ✔ postgres Pulled                                                   1.0s 
>  ✔ q2tg Pulled
> ```

一样的issuing

**Comment by clansty** [comment]
是因为使用的版本已经过期，并且现在 QQ bot 需要签名服务器才能使用。需要部署签名服务器
