### ISSUE TITLE
如何输入ticket

### ISSUE THREAD

**Issue by jizizr** [Clansty/Q2TG#123]
请使用此软件验证并输入 Ticket
请问怎么输入ticket

**Comment by qi-mooo** [comment]
需要ticket的时候你就 docker-compose up 就可以交互，输入完了再用 docker-compose up -d

**Comment by qi-mooo** [comment]
但是目前OICQ没有更新，输入了ticket之后也会风控下线，只能等OICQ更新

**Comment by clansty** [comment]
把 ticket 发给机器人就可以了

但是现在 oicq 不太稳定

**Comment by jizizr** [comment]
> 把 ticket 发给机器人就可以了 但是现在 oicq 不太稳定

登上了，感谢

**Comment by jizizr** [comment]
可以close了
