### ISSUE TITLE
[FEATURE] 添加签名服务器支持

### ISSUE THREAD

**Issue by XieXiLin2** [Clansty/Q2TG#125]
icqq 两周前添加了对配置 QSignServer 地址的支持，希望能添加对 QSignServer 地址的配置项。
icqq: sign_api_addr

**Comment by clansty** [comment]
现在最新的版本有这个支持，但是需要直接改数据库的字段

**Comment by StephenSSR** [comment]
> 现在最新的版本有这个支持，但是需要直接改数据库的字段

请问可以给个具体路径吗？谢谢

**Comment by richard-redtail** [comment]
我尝试修改了数据库中 “QqBot” 表的 “signApi” 字段，但日志中还是提示 “未配置签名API地址，登录/消息发送可能失败”，请问应该修改哪个字段呢？
