### ISSUE TITLE
[Bug Report?] 最新 Q2TG 镜像并未询问填写 signAPI 地址

### ISSUE THREAD

**Issue by gxres042** [Clansty/Q2TG#128]
拉取了刚刚更新的 Q2TG Docker 镜像
设置时并没有向我提问是否填写 signAPI
![image](https://github.com/Clansty/Q2TG/assets/53113178/83746703-3bc2-4330-b5fc-c256fc58d5a8)
不知这个 signAPI 如何触发并填写，请多多指教

**Comment by sbbbsbbb** [comment]
https://github.com/Clansty/Q2TG/commit/c3f83da7e099234b706c9512b566874b7fcd95db
Mac 才需要
<img width="490" alt="image" src="https://github.com/Clansty/Q2TG/assets/18375162/439548c5-fa5c-41ce-8da3-17dd32a7955b">

**Comment by gxres042** [comment]
玄学，以后再说吧

**Comment by lancer-wang** [comment]
我是哪个都有，但是都是报
![image](https://github.com/Clansty/Q2TG/assets/69783837/abf18112-53f8-4afd-b99a-d510ba13d499)

**Comment by clansty** [comment]
最新的 commit 应该修复了应该导致这个问题的问题
