### ISSUE TITLE
添加 signKey 配置项

### ISSUE THREAD

**Issue by Big-Cake-jpg** [Clansty/Q2TG#130]
unidbg-fetch-qsign 最新版本开始要求配置签名密钥用于鉴权，Q2TG 可否跟进？

**Comment by ccmuyuu** [comment]
输入时输入 http://ip:port/sign?key=yourkey 即可

**Comment by Big-Cake-jpg** [comment]
> 输入时输入 http://ip:port/sign?key=yourkey 即可

我实际这样填写的时候，Q2TG 会报错。
```
main_q2tg        | [2023-07-18T11:28:14.808] [ERROR] Main - UnhandledException:  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
main_q2tg        |     at new NodeError (node:internal/errors:393:5)
main_q2tg        |     at Function.from (node:buffer:328:9)
main_q2tg        |     at OicqClient.getSign (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/node_modules/icqq/lib/core/base-client.js:257:35)
main_q2tg        |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
main_q2tg        |     at async OicqClient.buildLoginPacket (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/node_modules/icqq/lib/core/base-client.js:1092:20)
main_q2tg        |     at async [FN_SEND_LOGIN] (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/node_modules/icqq/lib/core/base-client.js:705:21) {
main_q2tg        |   code: 'ERR_INVALID_ARG_TYPE'
main_q2tg        | }
```
> 实际上此时我已经手动修改数据库将签名服务器配置为了如上格式。

**Comment by ccmuyuu** [comment]
> > 输入时输入 http://ip:port/sign?key=yourkey 即可
> 
> 我实际这样填写的时候，Q2TG 会报错。
> 
> ```
> main_q2tg        | [2023-07-18T11:28:14.808] [ERROR] Main - UnhandledException:  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
> main_q2tg        |     at new NodeError (node:internal/errors:393:5)
> main_q2tg        |     at Function.from (node:buffer:328:9)
> main_q2tg        |     at OicqClient.getSign (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/node_modules/icqq/lib/core/base-client.js:257:35)
> main_q2tg        |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> main_q2tg        |     at async OicqClient.buildLoginPacket (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/node_modules/icqq/lib/core/base-client.js:1092:20)
> main_q2tg        |     at async [FN_SEND_LOGIN] (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/node_modules/icqq/lib/core/base-client.js:705:21) {
> main_q2tg        |   code: 'ERR_INVALID_ARG_TYPE'
> main_q2tg        | }
> ```
> 
> > 实际上此时我已经手动修改数据库将签名服务器配置为了如上格式。

抱歉，我测试这个的时候已经用了0.4.11的icqq 你可以等<a href=https://github.com/Clansty/Q2TG/pull/132#issue-1810395724>这个pr</a>合并，或者直接用我仓库里已经构建好的

**Comment by Big-Cake-jpg** [comment]
> 抱歉，我测试这个的时候已经用了0.4.11的icqq 你可以等[这个pr](https://github.com/Clansty/Q2TG/pull/132#issue-1810395724)合并，或者直接用我仓库里已经构建好的

非常感谢，但是我这边不知为何：可以登录，但是 TG -> QQ 会失败并报错
```
main_q2tg        | [2023-07-19T01:08:18.971] [ERROR] ForwardService - 0 - 从 TG 到 QQ 的消息转发失败 TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
main_q2tg        |     at new NodeError (node:internal/errors:393:5)
main_q2tg        |     at Function.from (node:buffer:328:9)
main_q2tg        |     at OicqClient.getSign (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/node_modules/icqq/lib/core/base-client.js:257:35)
main_q2tg        |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
main_q2tg        |     at async OicqClient.buildUniPktSign (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/node_modules/icqq/lib/core/base-client.js:777:20)
main_q2tg        |     at async OicqClient.sendUni (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/node_modules/icqq/lib/core/base-client.js:753:34)
main_q2tg        |     at async Group.sendMsg (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/node_modules/icqq/lib/group.js:304:29)
main_q2tg        |     at async ForwardService.forwardFromTelegram (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/build/services/ForwardService.js:611:24)
main_q2tg        |     at async onTelegramMessage (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/build/controllers/ForwardController.js:94:36)
main_q2tg        |     at async onMessage (/nix/store/mmlf8q76zaj0w05xamdxh0dyi8n98hvc-q2tg/libexec/q2tg/build/client/Telegram.js:80:25) {
main_q2tg        |   code: 'ERR_INVALID_ARG_TYPE'
main_q2tg        | }
```

**Comment by lancer-wang** [comment]
用最新版的也是token失效: [禁止登录]
是不是就没救了

**Comment by Big-Cake-jpg** [comment]
> 用最新版的也是token失效: [禁止登录] 是不是就没救了

你需要配置一个签名服务器。

**Comment by lancer-wang** [comment]
> > 用最新版的也是token失效: [禁止登录] 是不是就没救了
> 
> 你需要配置一个签名服务器。

我有搭签名服务器

**Comment by lancer-wang** [comment]
![image](https://github.com/Clansty/Q2TG/assets/69783837/bc45d8a5-64fc-41b9-88de-a396dc7cb6c7)

**Comment by lancer-wang** [comment]
> > 用最新版的也是token失效: [禁止登录] 是不是就没救了
> 
> 你需要配置一个签名服务器。

我用的是这个docker版本的1.1.5 你的是哪里的？
https://hub.docker.com/r/xzhouqd/qsign

**Comment by ccmuyuu** [comment]
> > > 用最新版的也是token失效: [禁止登录] 是不是就没救了
> > 
> > 
> > 你需要配置一个签名服务器。
> 
> 我用的是这个docker版本的1.1.5 你的是哪里的？ https://hub.docker.com/r/xzhouqd/qsign

docker的签名服务器请确保与q2tg容器跑在同一 /24 host，否则可能无法跨网段访问；我是直接运行的，试了两个号都可以

**Comment by lancer-wang** [comment]
> > > > 用最新版的也是token失效: [禁止登录] 是不是就没救了
> > > 
> > > 
> > > 你需要配置一个签名服务器。
> > 
> > 
> > 我用的是这个docker版本的1.1.5 你的是哪里的？ https://hub.docker.com/r/xzhouqd/qsign
> 
> docker的签名服务器请确保与q2tg容器跑在同一 /24 host，否则可能无法跨网段访问；我是直接运行的，试了两个号都可以

我用的是公网ip不是内网的
同一网段我也试了，也不行
