### ISSUE TITLE
在掉线重连后消息重复

### ISSUE THREAD

**Issue by StephenSSR** [Clansty/Q2TG#134]
在当前最新版本中，掉线自动重连后，接收消息会重复发送，与掉线次数挂钩，每多掉线一次，消息会多接收发送一次

**Comment by Big-Cake-jpg** [comment]
同样有此问题，目前我是在收到 TG Bot 发送的掉线通知后手动重启一次容器来临时解决。

**Comment by clansty** [comment]
同样有此问题

**Comment by ccmuyuu** [comment]
试试新的pr
