### ISSUE TITLE
[bug]@错误

### ISSUE THREAD

**Issue by qi-mooo** [Clansty/Q2TG#137]
当用户拥有两个或者以上的用户名则会变成@null
![Screenshot_2023-08-21-23-18-44-84_02708326f29fed657eaafc6ee6a8aa8a](https://github.com/Clansty/Q2TG/assets/59095213/931de686-662f-41b9-94e2-241fa8ab53f3)
![Screenshot_2023-08-21-23-18-31-61_02708326f29fed657eaafc6ee6a8aa8a](https://github.com/Clansty/Q2TG/assets/59095213/8a98c929-c6a2-4d52-9895-7a1e76a9f680)

**Comment by clansty** [comment]
fixed
