### ISSUE TITLE
更新icqq版本

### ISSUE THREAD

**Issue by Adlyq** [Clansty/Q2TG#143]
icqq@0.4.12 (Released on 2023/7/24)
出现
main_q2tg  | [2023-10-14T05:52:01.479] [WARN] [icqq] - token失效: [禁止登录]登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。(错误码：45)
main_q2tg  | [2023-10-14T05:52:01.480] [ERROR] [icqq] - [禁止登录]登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。
main_q2tg  | [2023-10-14T05:52:01.480] [ERROR] SetupController - 0 - 登录 OICQ 失败 [禁止登录]登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。
main_q2tg  | [禁止登录]登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。

**Comment by ccmuyuu** [comment]
试试我仓库里的？更新了没pr

**Comment by StephenSSR** [comment]
> 试试我仓库里的？更新了没pr
感谢更新，但是目前遇到了禁止8.9.78以下登录的问题，而qsign目前的txlib只支持到8.9.73，请问有什么解决办法吗QAQ

**Comment by ccmuyuu** [comment]
> > 试试我仓库里的？更新了没pr
> > 感谢更新，但是目前遇到了禁止8.9.78以下登录的问题，而qsign目前的txlib只支持到8.9.73，请问有什么解决办法吗QAQ

你用的是[这个qsign](https://github.com/fuqiuluo/unidbg-fetch-qsign)吗，不过老版本登不了估计是tx问题，我还没碰到

**Comment by StephenSSR** [comment]
> > > 试试我仓库里的？更新了没pr
> > > 感谢更新，但是目前遇到了禁止8.9.78以下登录的问题，而qsign目前的txlib只支持到8.9.73，请问有什么解决办法吗QAQ
> 
> 你用的是[这个qsign](https://github.com/fuqiuluo/unidbg-fetch-qsign)吗，1.1.9里面有63、68、70的，不过老版本登不了估计是tx问题

是的，第三方签名我只知道这个，现在腾讯对部分账号禁止低版本登录

**Comment by clansty** [comment]
已更新
