### ISSUE TITLE
你们这个为什么会把数据库清空啊？？？

### ISSUE THREAD

**Issue by lancer-wang** [Clansty/Q2TG#144]
我数据库其他表全没了

**Comment by lancer-wang** [comment]
![image](https://github.com/Clansty/Q2TG/assets/69783837/69e97ec4-33f8-4e07-b85d-7f9749b7a269)

**Comment by magisk317** [comment]
你们这个群，害人不浅（原谅我想到了那个梗。。

话说为啥要把这个数据库跟自己的其他项目/数据库放在一起呢？不是搞这个的，不是很清楚，我光这个项目的数据库都不知道删几回了。。。出问题一言不合就删了哈哈哈

**Comment by lancer-wang** [comment]
=

> 你们这个群，害人不浅（原谅我想到了那个梗。。
> 
> 话说为啥要把这个数据库跟自己的其他项目/数据库放在一起呢？不是搞这个的，不是很清楚，我光这个项目的数据库都不知道删几回了。。。出问题一言不合就删了哈哈哈

我不知道他们会删我其他表，放一起主要方便看

**Comment by clansty** [comment]
方便看你也不知道哪张表是哪个项目的吧

正常不应该给每个程序一个单独的数据库用户和对应的数据库嘛
