### ISSUE TITLE
上传文件会有上传中的提示

### ISSUE THREAD

**Issue by Narutojoy** [Clansty/Q2TG#153]
上传文件会有一个上传中的提示如图
![Snipaste_2023-12-15_19-37-58](https://github.com/Clansty/Q2TG/assets/25220944/3fe7af5c-5a1f-48eb-b025-6cb75bb5783d)

请问如何关闭这个提示呀

**Comment by clansty** [comment]
没有做关闭这个选项，欢迎 pr

**Comment by Narutojoy** [comment]
不会代码的我，难过了（哭

**Comment by clansty** [comment]
好好好，开心的时候给你加

**Comment by Narutojoy** [comment]
谢谢大佬！

**Comment by clansty** [comment]
增加了 `DISABLE_FILE_UPLOAD_TIP` 环境变量
