### ISSUE TITLE
获取头像的API可能出错

### ISSUE THREAD

**Issue by weclont** [Clansty/Q2TG#17]
当在机器人中设置群聊时，获取到的群组头像为与群号相同的QQ号的头像，是否为头像API设置出错了？

![photo_2022-06-20_09-54-44](https://user-images.githubusercontent.com/68319319/174511991-06e78ea9-f470-4af4-942d-fc2bb1723582.jpg)

![photo_2022-06-20_09-53-29](https://user-images.githubusercontent.com/68319319/174511899-df103a8a-69c9-4275-94c8-a7e7a444a298.jpg)

**Comment by shallowwang** [comment]
是这样的，我找了一下应该把获取群头像的api改成
http://p.qlogo.cn/gh/群号/群号/640/
但我不知道在哪改

**Comment by weclont** [comment]
> /refresh会把头像改成对的

感谢
