### ISSUE TITLE
wiki末尾启动命令问题

### ISSUE THREAD

**Issue by ZYGLQexplorer** [Clansty/Q2TG#20]
wiki的最末尾，启动命令有点问题，问题不大但是新手可能弄不明白
![](https://cos.zyglq.cn/blog/202206271129831.png)
这里应该是 'docker-compose up -d'

**Comment by clansty** [comment]
最新的版本确实是 docker 空格 compose

**Comment by clansty** [comment]
https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command
