### ISSUE TITLE
arm64 支持

### ISSUE THREAD

**Issue by QQ-War** [Clansty/Q2TG#22]
#docker logs -f q2tg
Prisma schema loaded from prisma/schema.prisma
Error: Unable to require(`/app/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node`)
 Error relocating /app/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node: __res_init: symbol not found
Prisma schema loaded from prisma/schema.prisma
Error: Unable to require(`/app/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node`)
 Error relocating /app/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node: __res_init: symbol not found

#my dockerfile:
 cat q2tg/dockerfile
FROM ghcr.io/clansty/q2tg:raincandy
RUN apk add --no-cache openssl libc6-compat

#my compose file:
q2tg:
    build: ./q2tg
    #image: ghcr.io/clansty/q2tg:raincandy
    #image: ghcr.io/clansty/q2tg:sha-aacc155@sha256:719cbf06b0eca6be04c7b8e73a25528f9710a1b072582aaf631186abd5975169
    container_name: q2tg
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./q2tg/data:/app/data
    environment:
      - TG_API_ID=7

**Comment by clansty** [comment]
请贴一下你宿主机 `uname -a` 的输出。我没有在 arm64 上测试过

**Comment by QQ-War** [comment]
Linux mainserver 5.13.0-1030-oracle #35~20.04.1-Ubuntu SMP Wed May 25 23:19:48 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by zsbai** [comment]
arm暂时还是不可用的，因为prisma当时无法在arm设备上运行（

**Comment by QQ-War** [comment]
试过了，确实amd64就可以，arm就不行，虽然有提供的arm镜像，自己加那些包也不行。
