### ISSUE TITLE
无法正常查看合并转发消息等，链接打开显示error

### ISSUE THREAD

**Issue by krau** [Clansty/Q2TG#23]
如图
![图片](https://user-images.githubusercontent.com/71133316/181151999-125d8f1a-1ede-428b-b20c-4b1e2f6ec362.png)
![Uploading 图片.png…]()

**Comment by clansty** [comment]
你的 Chat record viewer 有正确配置吗 包括服务端和配置文件

以及请等上传完成后再发送 issue

**Comment by krau** [comment]
> 你的 Chat record viewer 有正确配置吗 包括服务端和配置文件
> 
> 以及请等上传完成后再发送 issue

检查过全流程是按照q2tgv2的wiki配置的，chat record viewer仓库以导入方法设为的私有。请问是否还需要另去配置chat record viewer？

另外没有找到chat record viewer中的config.example.yaml，可否自行创建并写入readme中所给的配置？

附：上面没传完的图片
![图片](https://user-images.githubusercontent.com/71133316/181652041-47c41527-9a07-4466-8ec9-349aa0df4747.png)

**Comment by clansty** [comment]
[chatrecord-viewer-frontend](https://github.com/Clansty/chatrecord-viewer-frontend) 的 readme 似乎有点过时，是旧版本的，到时候更新一下。wiki 里面是最新的

**Comment by clansty** [comment]
你看一下你 pages 里面的变量是不是都写好了，特别是那个 KV。设置完之后需要重新部署一下

**Comment by krau** [comment]
> 你看一下你 pages 里面的变量是不是都写好了，特别是那个 KV。设置完之后需要重新部署一下

感谢回复！之前似乎是因为把KV的绑定设到了生产，改为preview并重新部署后已解决上述问题

**Comment by lancer-wang** [comment]
> > 你看一下你 pages 里面的变量是不是都写好了，特别是那个 KV。设置完之后需要重新部署一下
> 
> 感谢回复！之前似乎是因为把KV的绑定设到了生产，改为preview并重新部署后已解决上述问题

![image](https://user-images.githubusercontent.com/69783837/195788458-c91a4c03-646e-4d3c-8273-08635311b439.png)
具体应该如何操作啊?
我改了这里然后重新部署,打开还是error
然后这两个域名应该用哪个 啊
![image](https://user-images.githubusercontent.com/69783837/195788823-1ffbf7fc-702a-4c64-abc6-8a802e7e74b9.png)
