### ISSUE TITLE
临时会话支持

### ISSUE THREAD

**Issue by Leao9203** [Clansty/Q2TG#30]
当前部署基于时的 commit 为 72a30a014deac98c02c89f1f4c919b1613240963

报错的日志为 [log.txt](https://github.com/Clansty/Q2TG/files/9274162/log.txt)

机器人的回复为
![20220806_090227](https://user-images.githubusercontent.com/45661339/183227476-0d76ea10-a93d-45e3-97a8-9853521951f4.png)

**Comment by Leao9203** [comment]
顺带一提，在此前的 commit （a8ad7b26d957ead8108d008100ee6b6648c64321） 部署时未出现这个问题

**Comment by Leao9203** [comment]
好像不是好友，是临时会话

**Comment by clansty** [comment]
临时会话在制作的时候没有考虑过，因为我自己没有开启临时会话

**Comment by Leao9203** [comment]
啊这...好吧
