### ISSUE TITLE
TG的视频格式的GIF能否转换为图片GIF发送至QQ

### ISSUE THREAD

**Issue by sakarie9** [Clansty/Q2TG#32]
如题，现在的TG GIF发送到QQ的是视频，QQ方保存和转发都不太方便，能否转换成GIF再发送呢

**Comment by Leao9203** [comment]
> 如题，现在的TG GIF发送到QQ的是视频，QQ方保存和转发都不太方便，能否转换成GIF再发送呢

我觉得很难，因为你哪怕 TG 的客户端，GIF 也是以视频形式来保存的。

但是动态的贴纸是可以转换成 GIF 的，这波判 TG 全责（

**Comment by clansty** [comment]
可以考虑加转换

贴纸会转换主要是因为常用的都是那些贴纸，转换一次之后可以缓存
