### ISSUE TITLE
发送原图的支持

### ISSUE THREAD

**Issue by just-a-pony** [Clansty/Q2TG#33]
如题 目前无论是QQ发tg还是tg发QQ 都无法发送原图 会被压缩的非常糊 希望能添加对发送原图的支持

**Comment by clansty** [comment]
我对如何启用发送原图好像没什么想法，有没有什么推荐

以及现在在 tg 中「无压缩发送」会在 QQ 里发送原图

**Comment by just-a-pony** [comment]
可以在qq有人发送原图的时候 图片下方添加一个按钮 如果有人按了按钮 则获取原图 并修改刚刚发送的内容为原图（不大了解，希望没有说错的地方
