### ISSUE TITLE
部署后的设置转发步骤是否未写出？

### ISSUE THREAD

**Issue by htxzdfunny** [Clansty/Q2TG#38]
我参照 wiki 中的部署方式正确部署了一个实例并进行了 `/setup`
选择群组模式上线后，我想配置一个新转发，但我发现 wiki 中并没有写出如何配置一个新转发。
而机器人私聊中也没有出现命令列表，如下图
![image](https://user-images.githubusercontent.com/54425771/184477020-89e8a582-34de-44e9-ae79-a3109aa16816.png)
![image](https://user-images.githubusercontent.com/54425771/184477029-bfdf71e9-e207-42bf-a51c-505c61fdc27a.png)

群内也没有出现命令列表。
这是否是由于疏忽导致没有在 wiki 中写出设置转发的步骤，或是一个偶发性 bug 导致机器人没有正确配置显示指令列表？

**Comment by clansty** [comment]
是没有正常显示命令列表。命令是 /add

**Comment by clansty** [comment]
https://github.com/Clansty/Q2TG/commit/420d749b7f456835ee8d81e71f72913f65ad4f79
