### ISSUE TITLE
是需要登录telegarm机器人帐号才可以转发消息到QQ群吗

### ISSUE THREAD

**Issue by HeiLAAS** [Clansty/Q2TG#4]
Q群转发到TG是正常的，但是TG群的消息转发不到Q群.

**Comment by HeiLAAS** [comment]
![QQ截图20211003151609](https://user-images.githubusercontent.com/40287711/135744108-96074027-b800-47c1-bb04-a26cde64d6b6.png)
![QQ截图20211003151534](https://user-images.githubusercontent.com/40287711/135744115-c30d21d5-f6e6-4987-b1f1-d8749cec1b8f.png)
![QQ截图20211003151515](https://user-images.githubusercontent.com/40287711/135744116-572a84aa-5247-42e6-a849-f5d9a6d4ee9c.png)

**Comment by HougeLangley** [comment]
TG群机器人权限是否打开？

**Comment by Clansty** [comment]
需要关闭群聊隐私模式

**Comment by HeiLAAS** [comment]
整好了。
之后更新可以支持私聊通知吗.

**Comment by Clansty** [comment]
私聊转发？

暂时没这个打算，因为设计上是给群的运营者用的
