### ISSUE TITLE
添加实例之后如何删除

### ISSUE THREAD

**Issue by Leao9203** [Clansty/Q2TG#40]
在开了机器人之后，看到有添加其他实例的功能，于是就添加了两个

![image](https://user-images.githubusercontent.com/45661339/185948284-ed818fb5-4171-4c4c-abb0-5775815ab5f6.png)

但后面发现机子好像负载不了三个实例，于是就想要删掉，请问是否有办法来删掉通过这种方式添加的实例？

**Comment by Leao9203** [comment]
甚至在把 Bot 删除后仍在尝试登录，以至于出现报错（

> ![image](https://user-images.githubusercontent.com/45661339/185949960-c3ee20c3-0d19-45f1-aa56-da7961c2ce29.png)

**Comment by clansty** [comment]
手动进数据库删除
