### ISSUE TITLE
运行后没有开始转发，查看docker日志显示command not found: prisma

### ISSUE THREAD

**Issue by shallowwang** [Clansty/Q2TG#48]
![image](https://user-images.githubusercontent.com/53987645/189679443-17f82d87-db89-4e4f-915d-f69e079e5081.png)
之前一直用的好好的，今天突然这样，换服务器重新部署也还是

**Comment by shallowwang** [comment]
不知道是不是我的问题

**Comment by clansty** [comment]
大概是最新的镜像引入的问题

![image](https://user-images.githubusercontent.com/18461360/190636792-63c0a9f5-3c79-4071-9bd8-50bf138f654f.png)

这个 commit 可以跑

**Comment by lancer-wang** [comment]
> 

应该怎么改成这个commit?

**Comment by sakarie9** [comment]
> > 
> 
> 应该怎么改成这个commit?

`docker-compose.yaml` 里 `q2tg:raincandy` 修改成下面的
```
q2tg:
    image: ghcr.io/clansty/q2tg:sha-efc3f07
```

**Comment by lancer-wang** [comment]
> > > 
> > 
> > 
> > 应该怎么改成这个commit?
> 
> `docker-compose.yaml` 里 `q2tg:raincandy` 修改成下面的
> 
> ```
> q2tg:
>     image: ghcr.io/clansty/q2tg:sha-efc3f07
> ```

多谢

**Comment by ad2248** [comment]
我也有这个问题，估计要等作者修复了
