### ISSUE TITLE
TG 发送视频会造成机器人挂掉

### ISSUE THREAD

**Issue by HougeLangley** [Clansty/Q2TG#5]
TG 发送数秒（少于60秒）的视频会出现机器人漰溃，需要重启服务端机器人才能恢复。

**Comment by Clansty** [comment]
能否提供日志信息，我这里没有这个问题

以及检查一下 `ffmpeg` 命令是否可用

**Comment by HougeLangley** [comment]
> 能否提供日志信息，我这里没有这个问题
> 
> 以及检查一下 `ffmpeg` 命令是否可用

好的，我晚些时候到服务器里试试😉

**Comment by HougeLangley** [comment]
貌似最近这个问题没有了，将来碰到再说，非常感谢作者的努力。
