### ISSUE TITLE
扫码按钮没有被关闭

### ISSUE THREAD

**Issue by yuioto** [Clansty/Q2TG#52]
在网络环境不正常的时候启动，出现要求QQ重新验证，点扫码无反应。
经过数次重启后恢复正常，但扫码按钮依然存在，无法被关闭。如图所示。
即使重启 Telegram Desktop 也未能得到解决。
![IMG_20221003_223630_800.jpg](https://user-images.githubusercontent.com/68138727/193604932-b4e87d86-2e4a-423a-94e2-91fc19849a65.jpg)

**Comment by yuioto** [comment]
手机端正常。
在此问题期间，我没有启动过手机端。
![Capture+_2022-10-03-22-45-57.png](https://user-images.githubusercontent.com/68138727/193607203-81670d69-7f50-456c-a1df-b98181a511e6.png)

**Comment by clansty** [comment]
扫码登录已经被砍了，那个按钮是残留
