### ISSUE TITLE
转发失败

### ISSUE THREAD

**Issue by ayaka14732** [Clansty/Q2TG#54]
![](https://user-images.githubusercontent.com/68557794/194608667-5d8bdb45-2e70-41a6-9a02-9bdc9c0cd397.jpg)

![](https://user-images.githubusercontent.com/68557794/194609321-b39d6e06-eafa-4b0e-ac2c-4b20dcdfc53d.jpg)

**Comment by clansty** [comment]
这个应该是机器人掉线了

**Comment by ayaka14732** [comment]
已经解决了，解决方法是重启，重启之后要重新登录，需要输入手机验证码，手机收不到验证码，但是可以从 docker logs 中复制登录验证的 URL 到登录过 QQ 的手机上验证，验证成功后机器人没有反应，再重启一次就好了
