### ISSUE TITLE
希望qq表情包可以以sticker的形式在tg发出

### ISSUE THREAD

**Issue by zsbai** [Clansty/Q2TG#55]
之后想在telegram找到聊天记录里之前的图片时发现已经被表情包填满了

**Comment by clansty** [comment]
#6 

不过可以考虑在私聊里面这么搞

**Comment by zsbai** [comment]
> #6 
> 
> 
> 
> 不过可以考虑在私聊里面这么搞

可以考虑借鉴efb的方式，将名字放在表情包下方
![image](https://user-images.githubusercontent.com/62942942/194763036-3bbcfcf6-e35f-4a8b-9b2c-db1dfa79e34b.jpeg)

**Comment by clansty** [comment]
哦，可以做成按钮

可以加
