### ISSUE TITLE
请问下， 如何单向发送，如tg2qq 或 qq2tg 谢谢

### ISSUE THREAD

**Issue by mobilelifeful** [Clansty/Q2TG#71]
请问下， 如何单向发送，如tg2qq 或 qq2tg 谢谢

**Comment by Seele-Vollerei32** [comment]
已经实现了,群组里用`/disable_qq_forward`或`/disable_tg_forward`

**Comment by mobilelifeful** [comment]
@Seele-Vollerei32 谢谢啊 ，  但是无法搭建成功。逃了

**Comment by clansty** [comment]
请另开一个 issue 描述无法搭建的问题
