### ISSUE TITLE
Interested in Sponsoring the Project

### ISSUE THREAD

**Issue by ayaka14732** [Clansty/Q2TG#81]
I have been using this project for a long time and it's really a game-changer! It has made my life so much easier by eliminating the need for me to regularly check my QQ for new messages. I can now check them directly on Telegram, saving me a ton of time. I am beyond impressed with this project and its potential to make people's lives easier. Therefore, I am eager to sponsor it and help it grow even more! @Clansty Can you please consider opening up a GitHub sponsor option so that I can support this amazing project?

<img src="https://user-images.githubusercontent.com/68557794/211829006-25daf416-e350-41d8-8f6e-ef4560e7d38d.png" width="150px">

<img src="https://user-images.githubusercontent.com/68557794/211829026-c5578a9b-833c-4e05-902e-566150927956.png" width="150px">

**Comment by clansty** [comment]
I tried to enable GitHub Sponsors with these region, but I'm still in the waiting list

<img width="521" alt="image" src="https://user-images.githubusercontent.com/18461360/212214563-5d11c323-6073-4990-8228-c1da3680ec49.png">

**Comment by Seele-Vollerei32** [comment]
Just use the cryptocurrency (or WeChat/Alipay QR code)
