### ISSUE TITLE
[Feature] rainbowcat 分支能否支持禁用 UserBot 模式？

### ISSUE THREAD

**Issue by SerinaNya** [Clansty/Q2TG#83]
如题，UserBot 在一些情况下不是必要的。

main 分支似乎不需要 UserBot，但之所以使用 rainbowcat 分支，是为了使用新的特性。

如果 rainbowcat 分支可以禁用 UserBot 模式，我希望：保留大多数的功能，支持目前已经实现的最新的消息类型；  
如果开一个新的分支，我希望：同步支持 rainbowcat 的消息类型。

希望开发者能够采纳我的建议，谢谢。

**Comment by clansty** [comment]
目前 main 分支（1.x）版本是作为 legacy 版本存在的，支持禁用 UserBot。但是目前没有打算继续维护。如果有需要，也可以向该分支发送 PR。

raincandy（2.x）和 rainbowcat（3.x）分别相当于 stable 和 current 版本。raincandy 目前不会增加新的功能，但是会提供可用性的维护。rainbowcat 分区调整了数据库结构，不能很方便的从 raincandy 直接升级。目前会在不 break 数据库结构的情况下对 rainbowcat 进行功能更新。

由于 raincandy 和 rainbowcat 中的多个功能需要 UserBot，要是要提供关闭 UserBot 的选项会增大很多工作量，所以重构的时候就取消了 UserBot 的开关。我在使用 UserBot 的时候也没有遇到任何问题。

如果有人愿意维护可禁用 UserBot 的版本，可以在制作完成后发送 PR。我会考虑合并到 raincandy / rainbowcat 分支或者创建新的分支来维护它。

**Comment by SerinaNya** [comment]
~~补充一点，目前 UserBot 的配置方式是通过 Telegram API 进行 `bot.create()` 操作，然而我在接收验证码时出现了收不到的情况，并且这个问题困扰了不止我一个人。这也是我希望禁用 UserBot 的原因之一。~~

~~换个思路，能否支持以手动的方式配置 UserBot 呢？自行通过 BotFather 创建 Bot，并提供 API Token，以替代由程序自动创建的 Bot，是否可行？~~

~~由此引出思考，如果将 UserBot 的 Token 配置为 Main Bot 的 Token，（也就是说两个 Bot 的 Token 相同，）是否就是另一种变相禁用 UserBot 的方式呢？~~

当然，我毕竟不是很了解项目，如果我对 UserBot 的理解有误，还请指出，谢谢您。

**Comment by clansty** [comment]
你理解错了，UserBot 的含义是使用普通的用户帐号来作为机器人使用。目的是完成一些普通机器人帐号无法完成的操作，比如说自动创建群，以及检测消息撤回。

**Comment by SerinaNya** [comment]
很抱歉我对 UserBot 产生了错误的理解，它似乎是人形自走机器人。。。这是好的。

我将尝试为项目提交 PR 以尽可能达到我的目标。为了更好地理解代码逻辑，能否冒昧与您在 Telegram 上做详细且高效的沟通？（我之前注意到了您的 Telegram 账户在 Bio 里表达了对自己开发的开源项目的沟通方式的理解）

谢谢您。

**Comment by gxres042** [comment]
作为以前的相关人员，我不是很喜欢 UserBot。
- UserBot 限制了能够操纵的管理员。也就是说，在普通情况下，如果需要添加转发只能由我来操作，其他人完全不可以操作；
- UserBot 限制了你的设备注销行动。我不能一键清理所有未知的设备，因为一旦一键清除将让 Q2TG 无法登录 Telegram Account，并且在设备列表里无法看到 Q2TG 的任何痕迹，至少我是这样的。
- 作为 UserBot 号主，我在 Telegram 删除自己的消息并不会在 QQ 端撤回。**偶尔也能撤回成功，但是概率不大**。

非任何不满和发泄，我只是平静的去讲述我对 UserBot 的不满。

**Comment by Nofated095** [comment]
https://github.com/Nofated095/Q2TG

可以使用这个 Fork 达到禁用 UserBot 的目的，但是这个 Fork 对于 Q2TG 的 rainbowcat 是一个破坏性更新，并没有增加可开关的 UserBot 功能，而是直接将 UserBot 从群组模式中抹除并且阉割了个人模式。请使用者斟酌考虑。
