### ISSUE TITLE
无法使用Android设备登陆

### ISSUE THREAD

**Issue by WorldTheDebug** [Clansty/Q2TG#86]
当我选择使用“Android”设备登陆时，终端输出「OICQ版本过低，点击更新」但tgbot却不输出，导致我无法进行更新，大家有Android登陆的有过这种情况吗？

**Comment by Nofated095** [comment]
建议不使用 Android 设备登录，Android 设备很容易造成风控，建议用 macOS 或 iPad 来排除问题。

**Comment by EasonHuang1212** [comment]
> 建议不使用 Android 设备登录，Android 设备很容易造成风控，建议用 macOS 或 iPad 来排除问题。

现在iPad登录也提示版本过低了。。。。

**Comment by Nofated095** [comment]
> > 建议不使用 Android 设备登录，Android 设备很容易造成风控，建议用 macOS 或 iPad 来排除问题。
> 
> 现在iPad登录也提示版本过低了。。。。

并没有，可能是你那边风控了，比较强的风控时不看你设备类型

**Comment by clansty** [comment]
请向 OICQ 提 issue
