### ISSUE TITLE
Unable get AnonChannel's user nickname

### ISSUE THREAD

**Issue by qwq233** [Clansty/Q2TG#9]
如题 如果用匿名频道发言 会提示Channel (老版本tg也是显示这个 应该是api没升级的问题)

qq side:
![image](https://user-images.githubusercontent.com/20317838/150766636-19381f76-6496-4a84-a8a3-e8deeab1c5f6.png)

tg side:
![image](https://user-images.githubusercontent.com/20317838/150767368-5edcb45f-12bf-46dc-a53e-c297f0a82168.png)

**Comment by clansty** [comment]
看起来没有这个问题

**Comment by qwq233** [comment]
> 看起来没有这个问题

看看Open这个issue的日期(
