### ISSUE TITLE
无法转发包含多个图片的QQ聊天信息

### ISSUE THREAD

**Issue by zhishixiang** [Clansty/Q2TG#94]
试图转发此类信息时会出现以下提示：
![image](https://user-images.githubusercontent.com/59593524/216863710-fde3628c-35a2-42ee-9206-08fb6ec4818b.png)
![image](https://user-images.githubusercontent.com/59593524/216863750-938723e6-90d3-4f77-9315-53f68d770c26.png)

**Comment by ghost** [comment]
我这里试了一下好像可以转
![图片](https://user-images.githubusercontent.com/30648722/218787925-35340f7f-6143-4658-b640-24f087a87a20.png)
![图片](https://user-images.githubusercontent.com/30648722/218787976-cf6a9e13-1a68-446e-ad45-75a9ef6832bf.png)
