### ISSUE TITLE
版本过低，禁止登录

### ISSUE THREAD

**Issue by sunuuc** [Clansty/Q2TG#96]
版本过低，禁止登录
![IMG_20230220_103948](https://user-images.githubusercontent.com/77818773/219997444-c8e2ed54-54d8-4a93-8a94-81e1703017bf.jpg)
一开始是手表登录

**Comment by Lidociane** [comment]
一样，昨天3:40的时候就掉线，今天就提示版本过低。

**Comment by SelfEnough** [comment]
一样

**Comment by Xander-C** [comment]
一样，也是20号开始的，ipad登录

**Comment by lancer-wang** [comment]
+1

**Comment by lancer-wang** [comment]
找到个解决方法，去你yaml 配置文件里面写的data的目录
里面有个文件夹名字是你qq号
删掉然后 docker restart main_q2tg
就行了

**Comment by Xander-C** [comment]
> 找到个解决方法，去你yaml 配置文件里面写的data的目录 里面有个文件夹名字是你qq号 删掉然后 docker restart main_q2tg 就行了

已解决，感谢

**Comment by zhishixiang** [comment]
> 找到个解决方法，去你yaml 配置文件里面写的data的目录 里面有个文件夹名字是你qq号 删掉然后 docker restart main_q2tg 就行了

还真行，感谢

**Comment by origami-owo** [comment]
https://github.com/takayama-lily/oicq/issues/507#issuecomment-1455951424  看看这个

**Comment by VEWION** [comment]
再次提示版本过低无法使用

**Comment by VEWION** [comment]
请问这项目是oicq不更新就无望了吗…已经一个月因为登录协议版本过低导致不能用了…

**Comment by t-satoru** [comment]
今天我被踢下线之后就彻底登不上 Q2TG 了

**Comment by Nofated095** [comment]
oicq版本低其实问题不大，和程序关系也不大（ 问题是出在腾讯对机器人的风控上，在风控后 Q2TG 会通知机器人下线。如果你发现你在正常使用 Q2TG 时莫名出现了 QQ 下线提醒（且重启后依旧提示 QQ 版本低），大概率是 QQ 机器人被风控，oicq 禁止登录。在风控后马上进行重新登录大概率因为腾讯风控没结束导致无法登录，按照一些教程删除数据是有可能重新登录 QQ 的，但是有可能造成更严重的风控。

正确做法是使用腾讯官方最新的 Android 或者 iOS 客户端（尤其针对 Android，务必认准官方 QQ（或 TIM）最新版，很多第三方修改版并不能起作用）登录被风控的 QQ。一般来说在手机端使用一段时间 QQ，发送一些比较好判断的人类消息即可有概率降低风控。一般来说风控会持续几个小时，多登录手机 QQ 给你的群发点消息就能解除风控。到时候再删掉 data 重新登录应该能解决问题。

以及建议不要在一台机子上部署太多 Q2TG 实例，小心腾讯给你一锅端。

**Comment by VEWION** [comment]
> oicq版本低其实问题不大，和程序关系也不大（ 问题是出在腾讯对机器人的风控上，在风控后 Q2TG 会通知机器人下线。如果你发现你在正常使用 Q2TG 时莫名出现了 QQ 下线提醒（且重启后依旧提示 QQ 版本低），大概率是 QQ 机器人被风控，oicq 禁止登录。在风控后马上进行重新登录大概率因为腾讯风控没结束导致无法登录，按照一些教程删除数据是有可能重新登录 QQ 的，但是有可能造成更严重的风控。
> 
> 正确做法是使用腾讯官方最新的 Android 或者 iOS 客户端（尤其针对 Android，务必认准官方 QQ（或 TIM）最新版，很多第三方修改版并不能起作用）登录被风控的 QQ。一般来说在手机端使用一段时间 QQ，发送一些比较好判断的人类消息即可有概率降低风控。一般来说风控会持续几个小时，多登录手机 QQ 给你的群发点消息就能解除风控。到时候再删掉 data 重新登录应该能解决问题。
> 
> 以及建议不要在一台机子上部署太多 Q2TG 实例，小心腾讯给你一锅端。

手机官方app同ip长时间登录着QQ所以不存在这原因导致的风控，用efb+go-cqhttp更新最新协议后也能正常登录长时间使用，奈何该项目特性支持不太行(比如回复支持之类)所以不太想用，综上所述已经基本确定是登录协议过低问题了

**Comment by t-satoru** [comment]
oicq 上游的上次 commit 还是三月份，结合最近 QQNT 的重构，很难不让人怀疑腾讯那边在砍协议
不过反正都登陆不上，大不了再放几天，反正登不上对于我们这些只会用不会开发的平民老百姓也只能摆

**Comment by Nofated095** [comment]
我又回看了一下，有可能像你所说的那样，但我仍持保留意见

但目前来看，我四月份新部署几个 Q2TG 都可以在现有 https://github.com/Clansty/Q2TG/commit/2b6e7af6a128204d354b1e37a76cb5d5f8360942
上的构建，用先前版本的 oicq 正常在 Q2TG 上登录 QQ 机器人。

如果有机会的话，建议试试全新重新部署，可能有一定概率能登录上 QQ 机器人也说不定。目前 Q2TG 对于 QQ 机器人风控重登录、临时换号确实有支持不佳的情况（
________________________________
发件人: VEWION ***@***.***>
发送时间: Monday, April 24, 2023 8:20:06 PM
收件人: Clansty/Q2TG ***@***.***>
抄送: Nofated095 ***@***.***>; Comment ***@***.***>
主题: Re: [Clansty/Q2TG] 版本过低，禁止登录 (Issue #96)


oicq版本低其实问题不大，和程序关系也不大（ 问题是出在腾讯对机器人的风控上，在风控后 Q2TG 会通知机器人下线。如果你发现你在正常使用 Q2TG 时莫名出现了 QQ 下线提醒（且重启后依旧提示 QQ 版本低），大概率是 QQ 机器人被风控，oicq 禁止登录。在风控后马上进行重新登录大概率因为腾讯风控没结束导致无法登录，按照一些教程删除数据是有可能重新登录 QQ 的，但是有可能造成更严重的风控。

正确做法是使用腾讯官方最新的 Android 或者 iOS 客户端（尤其针对 Android，务必认准官方 QQ（或 TIM）最新版，很多第三方修改版并不能起作用）登录被风控的 QQ。一般来说在手机端使用一段时间 QQ，发送一些比较好判断的人类消息即可有概率降低风控。一般来说风控会持续几个小时，多登录手机 QQ 给你的群发点消息就能解除风控。到时候再删掉 data 重新登录应该能解决问题。

以及建议不要在一台机子上部署太多 Q2TG 实例，小心腾讯给你一锅端。

手机官方app同ip长时间登录着QQ所以不存在这原因导致的风控，用efb+go-cqhttp更新最新协议后也能正常登录长时间使用，奈何该项目特性支持不太行(比如回复支持之类)所以不太想用，综上所述已经基本确定是登录协议过低问题了

―

**Comment by VEWION** [comment]
> 我又回看了一下，有可能像你所说的那样，但我仍持保留意见 但目前来看，我四月份新部署几个 Q2TG 都可以在现有 [2b6e7af](https://github.com/Clansty/Q2TG/commit/2b6e7af6a128204d354b1e37a76cb5d5f8360942) 上的构建，用先前版本的 oicq 正常在 Q2TG 上登录 QQ 机器人。 如果有机会的话，建议试试全新重新部署，可能有一定概率能登录上 QQ 机器人也说不定。目前 Q2TG 对于 QQ 机器人风控重登录、临时换号确实有支持不佳的情况（
> […](#)

已多次尝试全新安装依然不行，按照上游oicq的issue里的说法是按照QQ号慢慢踢除的，我前阵子也是一个QQ号被踢后不能重新登录，另一个能正常使用，再过大概一个星期多才两个都提示版本过低，看icqq有针对过这问题处理所以其他bot项目基本都用icqq替换oicq就能继续正常使用了，看Q2TG以前也有尝试过替换成icqq但回滚了，不知道是不是遇到什么适配问题

**Comment by lancer-wang** [comment]
我试了下，有个用go-cqhttp的桥接能用
为啥这里不改用gocq

**Comment by Nofated095** [comment]
Welcome PR
________________________________
发件人: lancer-wang ***@***.***>
发送时间: Tuesday, April 25, 2023 1:56:51 PM
收件人: Clansty/Q2TG ***@***.***>
抄送: Nofated095 ***@***.***>; Comment ***@***.***>
主题: Re: [Clansty/Q2TG] 版本过低，禁止登录 (Issue #96)


我试了下，有个用go-cqhttp的桥接能用
为啥这里不改用gocq

―

**Comment by clansty** [comment]
欢迎 pr
